#!/bin/bash
RUNDIR=$(pwd)
NONMEMLICENSEDIR=/opt/NONMEM/license
INTELLICENSEDIR=/opt/intel/licenses
DOCKERIMAGE=humanpredictions/psn

INTELLICENSEARG=""
if [ -d "${INTELLICENSEDIR}" ]; then \
    INTELLICENSEARG=-v "$INTELLICENSEDIR":/opt/intel/licenses
fi

docker run --rm --user=$(id -u):$(id -g) \
       -v "$NONMEMLICENSEDIR":/opt/NONMEM/nm_current/license \
       $INTELLICENSEARG \
       -v "$RUNDIR":/tmp \
       -w /tmp \
       $DOCKERIMAGE $@
